### ISSUE TITLE
[FEATURE]Compare to FasterTransformer

### ISSUE THREAD

**Issue by HoratioJSY** [OpenBMB/BMInf#12]
**Is there any comparison between BMInf and Nvidia's FasterTransformer?**

**I would like to use some tools to improve our model's inference performance. BMInf is great, and it seems like use CUDA implementation to boost inference performance, just like [FasterTransformer](https://github.com/NVIDIA/FasterTransformer). So, is there any comparison in inference time between BMInf and FasterTransformer?**

**Comment by a710128** [comment]
We haven't compared which is faster. But as far as I am concerned, FasterTransformer will be faster on a high performance platform. 
BMInf is designed to be able to run giant models in low-resource environments, and not much performance detail has been considered currently. We don't use FasterTransformer now because the implementation details of CPM are not quite the same as FasterTransformer.
We are going to optimize the efficiency on high performance platforms in later releases.
